// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Y4yhJ5gERGkJtV0CiqkovhCsChDhxfE',
    appId: '1:172034106942:web:97e0f2626c673263b9d36f',
    messagingSenderId: '172034106942',
    projectId: 'immoagence-364b7',
    authDomain: 'immoagence-364b7.firebaseapp.com',
    storageBucket: 'immoagence-364b7.firebasestorage.app',
    measurementId: 'G-EH4GX8V7JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLjJL0LJAgMqKautVACjMS9JZ0wfvoIW8',
    appId: '1:172034106942:android:f4047fc62ef41756b9d36f',
    messagingSenderId: '172034106942',
    projectId: 'immoagence-364b7',
    storageBucket: 'immoagence-364b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKm3jsbMrcwxyGGJRpnWn2MosPhaKPjEU',
    appId: '1:172034106942:ios:5088c4173f6ee004b9d36f',
    messagingSenderId: '172034106942',
    projectId: 'immoagence-364b7',
    storageBucket: 'immoagence-364b7.firebasestorage.app',
    iosBundleId: 'com.example.immoAgence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKm3jsbMrcwxyGGJRpnWn2MosPhaKPjEU',
    appId: '1:172034106942:ios:5088c4173f6ee004b9d36f',
    messagingSenderId: '172034106942',
    projectId: 'immoagence-364b7',
    storageBucket: 'immoagence-364b7.firebasestorage.app',
    iosBundleId: 'com.example.immoAgence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Y4yhJ5gERGkJtV0CiqkovhCsChDhxfE',
    appId: '1:172034106942:web:800f975cb8b14584b9d36f',
    messagingSenderId: '172034106942',
    projectId: 'immoagence-364b7',
    authDomain: 'immoagence-364b7.firebaseapp.com',
    storageBucket: 'immoagence-364b7.firebasestorage.app',
    measurementId: 'G-VN6R30YSKK',
  );
}
